definitions:
  structs.CommonResponse:
    properties:
      data: {}
      failed:
        type: integer
      message:
        type: string
      resultCount:
        type: integer
      statusCode:
        type: integer
      success:
        type: integer
      total:
        type: integer
    type: object
  structs.CreateUser:
    properties:
      email:
        example: example@email.com
        type: string
      password:
        example: password123
        type: string
      role:
        example: superadmin
        type: string
      username:
        example: John Doe
        type: string
    type: object
  structs.Login:
    properties:
      email:
        example: developer@mail.com
        type: string
      password:
        example: password
        type: string
    type: object
  structs.PageView:
    properties:
      endDt:
        example: "2024-05-11"
        type: string
      mdn:
        example: "081284088408"
        type: string
      page:
        example: 1
        type: integer
      shift:
        example: sore
        type: string
      startDt:
        example: "2024-05-11"
        type: string
      status:
        example: 20
        type: integer
      view:
        example: 10
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: User Login
      parameters:
      - description: request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/structs.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.CommonResponse'
      summary: User Login
      tags:
      - Auth
  /api/kpi/{database}/list:
    post:
      consumes:
      - application/json
      description: Measure KPI of each transaction
      parameters:
      - description: request body
        in: body
        name: data
        schema:
          $ref: '#/definitions/structs.PageView'
      - description: database path argument
        in: path
        name: database
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.CommonResponse'
      summary: List Data KPI
      tags:
      - KPI
  /api/sales/{database}/periode:
    get:
      consumes:
      - application/json
      description: Get Sales, PPH22 and Sales Net
      parameters:
      - description: query param
        in: query
        name: startDate
        type: string
      - description: query param
        in: query
        name: endDate
        type: string
      - description: database path argument
        in: path
        name: database
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.CommonResponse'
      summary: Get Sales By Date
      tags:
      - Sales
  /api/user/create:
    post:
      consumes:
      - application/json
      description: Create New User
      parameters:
      - description: request body
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/structs.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.CommonResponse'
      summary: Create New User
      tags:
      - User
  /api/user/delete:
    delete:
      consumes:
      - application/json
      description: Delete User By ID
      parameters:
      - description: query param
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.CommonResponse'
      summary: Delete User By ID
      tags:
      - User
  /api/user/list:
    get:
      consumes:
      - application/json
      description: Get All User With Pagination
      parameters:
      - description: query param page
        in: query
        name: page
        type: string
      - description: query param view
        in: query
        name: view
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.CommonResponse'
      security:
      - BearerAuth: []
      summary: Get All User
      tags:
      - User
  /api/user/search:
    get:
      consumes:
      - application/json
      description: Get User By ID
      parameters:
      - description: query param
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/structs.CommonResponse'
      summary: Get User By ID
      tags:
      - User
swagger: "2.0"
