# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["development"]
jobs:
  deployment:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy 36
        uses: appleboy/ssh-action@master
        with:
          host: 36.92.58.82
          username: eps
          password: dhani2001
          port: 22
          script: |
            pid=$(lsof -ti :1523)
            kill -9 $pid && cd go/src/eps-backend
            rm -rf pid.txt eps-api nohup.out go.mod go.sum && git pull origin development && go mod init
            go mod tidy && go build -o eps-api && nohup ./eps-api > /dev/null 2>&1 & echo $! > pid.txt
            pid=$(cat pid.txt)
            if ps -p $pid > /dev/null; then
              echo "Nohup process with PID $pid is running."
            else
              echo "Nohup process with PID $pid is not running."
            exit 1  # Exit with an error code if the process is not running
            fi
              echo "Deployment completed successfully"
            exit 0
