# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["development"]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.18"
  deployment:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - name: Deploy 36
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            pid=$(lsof -ti :1523)
            kill -9 $pid && cd go/src/eps-backend
            rm -rf deployment_pid.txt eps-api nohup.out go.mod go.sum && git pull origin development && go mod init
            go mod tidy && go build -o eps-api && nohup ./eps-api &
            echo $! > deployment_pid.txt
        
      - name:
        id: wait
        run: | 
        while kill -0 $(cat pid.txt) >/dev/null 2>&1; do
          sleep 5
        done 

      - name: Process completed, workflow finished
        if: always()
        run: |
        echo "Process completed, finishing workflow."
